name: Build and Push to Docker Hub (DISABLED)

on:
  # Disabled - requires DOCKERHUB_USERNAME and DOCKERHUB_TOKEN secrets
  # push:
  #   branches: [ main ]
  workflow_dispatch:  # Manual trigger only

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: false  # Disable this job
    
    steps:
    - name: Info
      run: |
        echo "This workflow is disabled because Docker Hub secrets are not configured."
        echo "To enable:"
        echo "1. Create Docker Hub account"
        echo "2. Generate access token"
        echo "3. Add DOCKERHUB_USERNAME and DOCKERHUB_TOKEN to repository secrets"
        echo "4. Remove 'if: false' condition from this job"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/upguard-cyberrisk-mcp-server
        tags: |
          type=ref,event=branch
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }} 