name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Run unit tests
      run: npm test
      env:
        UPGUARD_API_KEY: test-api-key-for-testing
        NODE_ENV: test
    
    - name: Run tests with coverage
      run: npm run test:coverage
      env:
        UPGUARD_API_KEY: test-api-key-for-testing
        NODE_ENV: test
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
    
    - name: Run integration tests
      run: npm run test:integration
      env:
        UPGUARD_API_KEY: test-api-key-for-testing
        TEST_MODE: http
        NODE_ENV: test
    
    - name: Check test coverage thresholds
      run: |
        npm run test:coverage -- --coverageThreshold='{
          "global": {
            "statements": 50,
            "branches": 70,
            "functions": 30,
            "lines": 50
          }
        }'
      env:
        UPGUARD_API_KEY: test-api-key-for-testing
        NODE_ENV: test

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run security audit
      run: npm audit --audit-level=moderate
    
    - name: Run dependency check
      run: npx audit-ci --moderate

  build:
    runs-on: ubuntu-latest
    needs: [test, security]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build documentation
      run: npm run docs:generate
    
    - name: Validate package
      run: npm pack --dry-run 